### PR TITLE
Add SysML To conference list

### PR DESCRIPTION
**Pull request by alexandraj777**
http://www.sysml.cc/index.html#body

### CODE REVIEW

**Comment by alexandraj777** [comment]
Left submission deadline as strikethrough rather than "CFP Passed" so that viewers have more context to start planning for next year's submissions.

**Comment by alexandraj777** [comment]
cc @reshamas @ledell

**Comment by ledell** [comment]
@reshamas do you want to just put "CFP Past" or a strikethrough of the date like @alexandraj777 has here?  I don't care either way (I agree that it's nice to have the extra context).

**Comment by reshamas** [comment]
thanks @alexandraj777 @ledell I think it's good to have the strikethrough.  So when people look at past years, they have some idea of when the CFP is due, since it is not available all year round on the website.

**Pull request merged**
